DROP TABLE IF EXISTS `#__pbbooking_emails`;
CREATE TABLE `#__pbbooking_emails` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email_tag` varchar(64) DEFAULT NULL,
  `description` text,
  `emailbody` text,
  `emailsubject` varchar(512) DEFAULT NULL,
  `subscriber` tinyint(1) DEFAULT '0',
  `uses_twig` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (1,'client_validation_email','This is the main email sent to the client on client validation workflows.','<p>Hi |*firstname*| |*lastname*|</p>\r\n<p>Thank you for choosing us for your next treatment. Please click the below link to validate your appointment with us.</p>\r\n<p>|*URL*|</p>\r\n<p>You\\\'re booking details are</p>\r\n<p>|*booking_details*|</p>','Your Treatment Verification',0,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (2,'auto_validated_appt_email','This email is sent to the client when using Auto Validation','<p>Hi |*firstname*| |*lastname*|</p>\r\n\r\n<p><strong>This is your auto validated appt confirmation</strong></p>\r\n\r\n\r\n<p>Thank you for choosing us for your next treatment.</p>\r\n\r\n\r\n\r\n<p>You\\\'re booking details are</p><p>|*booking_details*|</p>','Your Auto Validated Appt Confirmation',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (3,'admin_validation_pending_email','This email is set to the client when an Admin Validated booking is in a PENDING state.	','<p>Hi |*firstname*| |*lastname*|</p>\r\n\r\n<p><strong>This is your admin validation pending appt confirmation</strong></p>\r\n\r\n\r\n<p>Thank you for choosing us for your next treatment.</p>\r\n\r\n\r\n\r\n<p>You\\\'re booking details are</p><p>|*booking_details*|</p>','Your Admin Validation Pending',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (4,'admin_validation_confirmed','This email is sent to the client when an Admin Validated appointment has been CONFIRMED.	','<p>Hi |*firstname*| |*lastname*|</p>\r\n\r\n<p><strong>This is your admin validation confirmed appt confirmation</strong></p>\r\n\r\n\r\n<p>Thank you for choosing us for your next treatment.</p>\r\n\r\n\r\n\r\n<p>You\\\'re booking details are</p><p>|*booking_details*|</p>','Your Admin Validation Confirmed',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (5,'admin_payment_confirmed_email','This email is sent to the admin when a paid booking has been confirmed.  ie. paid.		','<p>Hi Admin</p>\r\n\r\n<p>There is a new paid booking in the calendar.</p>\r\n','Admin Paid Booking Confirmation',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (6,'client_payment_confirmed_email','This email is sent to the client when a booking has been paid for.	','<p>Hi |*firstname*| |*lastname*|</p>\r\n\r\n<p><strong>This is your client paid booking confirmation.</strong></p>\r\n\r\n\r\n<p>Thank you for choosing us for your next treatment.</p>\r\n\r\n\r\n\r\n<p>You\'re booking details are</p><p>|*booking_details*|</p>','Your Paid Booking Confirmation',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (7,'reminder_email','This email is sent to the client when a reminder is emailed.','Hi, This is a reminder.\r\n\r\nYour booking details are:\r\n\r\n|*booking_details*|','This is a reminder email',0,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (8,'survey_email','This email is sent to request a survey.','<p>\r\n  Hi,\r\n</p>\r\n\r\n<p>We\'d love it if you\'d take a short survey about your recent experience.</p>\r\n\r\n<p>\r\n  |*URL*|\r\n</p>','Please take a short survey.',0,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (9,'admin_notification','This email is sent to the admin when a new appointment is validated','<p>There is a new validated appointment in the diary. Details are below:</p> <p>|*booking_details*|</p>','New Validated Appointment',0,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (10,'admin_created_appt','This email is sent to the client when an ADMIN creates an appointment for them','<p>Hi |*firstname*| |*lastname*|</p> <p>Thank you for choosing us for your next treatment</p><p>You\\\'re booking details are</p> <p>|*booking_details*|</p>','Your New Appointment',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (11,'admin_deleted_appt','This email is sent to the client when an ADMIN deletes an appointment for them','<p>Hi |*firstname*| |*lastname*|</p> \r\n<p>An admin has deleted your appointment with us.</p> \r\n','Admin Deleted Appointment',1,0);
INSERT INTO `#__pbbooking_emails` (`id`, `email_tag`, `description`, `emailbody`, `emailsubject`, `subscriber`, `uses_twig`) VALUES (12,'admin_modified_appt','This email is sent to the client when an ADMIN modifies an appointment for them','<p>Hi |*firstname*| |*lastname*|</p> \r\n\r\n<p>An admin has modified your appointment time with us.</p> \r\n<p>You\\\'re booking details are</p> <p>|*booking_details*|</p>','Admin Modified Appointment',1,0);




