<?php
/**
 * Created by     Eric Fernance
 * User:          Eric Fernance
 * Website:       http://hotchillisoftware.com
 * License:       GPL v2
 */


if (!defined('JPATH_BASE')) die();


class PbbookingModelSms extends JModelAdmin {

  /**
   * Constructor.
   *
   * @param   array  $config  An optional associative array of configuration settings.
   */
  public function __construct($config = array())
  {


      parent::__construct($config);
  }



  public function getForm($data = array(), $loadData = true)
	{
		// Get the form.
		$form = $this->loadForm('com_pbbooking.sms', 'sms', array('control' => 'jform', 'load_data' => $loadData));

    if (empty($form))
		{
			return false;
		}

		return $form;
	}


  public function getTable($name = '', $prefix = 'Table', $options = array())
  {
      return parent::getTable("Sms", "PbbookingTable", $options); // TODO: Change the autogenerated stub
  }


  protected function loadFormData()
  {
      $data = $this->getItem();
      return $data;
  }



}
